# Generated by Django 3.0.2 on 2020-02-01 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            "RENAME TABLE `login` TO `login2`;"
        )
    ]
