# Generated by Django 2.2.1 on 2019-05-19 02:50

from django.db import migrations, models
import django.utils.timezone
import users.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'login',
                'managed': False,
            },
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='login',
            name='is_superuser',
            field=models.BooleanField(default=False,
                                      help_text='Designates that this user has all permissions without explicitly assigning them.',
                                      verbose_name='superuser status')
        ),
        migrations.AlterField(
            model_name='login',
            name='user_permissions',
            field=models.BooleanField(default=False,
                                      help_text='Designates that this user has all permissions without explicitly assigning them.',
                                      verbose_name='superuser status')
        ),
        migrations.AlterField(
            model_name='login',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name')
        ),
        migrations.AlterField(
            model_name='login',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name')
        ),
        migrations.AlterField(
            model_name='login',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.',
                                      verbose_name='staff status')
        ),
        migrations.AlterField(
            model_name='login',
            name='is_active',
            field=models.BooleanField(default=True,
                                      help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
                                      verbose_name='active')
        ),
        migrations.AlterField(
            model_name='login',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')
        ),
    ]
