# Generated by Django 3.0.2 on 2020-02-01 23:55

from django.db import migrations, models
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('users', '0001_backup_login_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(db_column='account_id', primary_key=True, serialize=False, verbose_name='Account ID')),
                ('username', models.CharField(db_column='userid', max_length=23, unique=True)),
                ('password', models.CharField(db_column='user_pass', max_length=32)),
                ('sex', models.CharField(choices=[('M', '👦🏻'), ('F', '👧🏻')], default='F', max_length=1, verbose_name='Gender')),
                ('email', models.CharField(max_length=39, unique=True)),
                ('group_id', models.IntegerField(default=0)),
                ('state', models.PositiveIntegerField(choices=[(0, 'Active'), (1, 'Banned')], default=0, verbose_name='RO State')),
                ('unban_time', models.PositiveIntegerField(blank=True, default=0)),
                ('expiration_time', models.PositiveIntegerField(blank=True, default=0)),
                ('logincount', models.PositiveIntegerField(blank=True, default=0)),
                ('last_login', models.DateTimeField(blank=True, db_column='lastlogin', null=True)),
                ('last_ip', models.CharField(blank=True, max_length=100)),
                ('birthdate', models.DateField(blank=True, default='2019-05-19', null=True)),
                ('character_slots', models.PositiveIntegerField(default=12)),
                ('pincode', models.CharField(blank=True, max_length=4)),
                ('pincode_change', models.PositiveIntegerField(blank=True, default=0)),
                ('vip_time', models.PositiveIntegerField(blank=True, default=0)),
                ('old_group', models.IntegerField(blank=True, default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'login',
                'managed': True,
            },
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Login2',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=23)),
                ('user_pass', models.CharField(max_length=32)),
                ('sex', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=39)),
                ('group_id', models.IntegerField()),
                ('state', models.PositiveIntegerField()),
                ('unban_time', models.PositiveIntegerField()),
                ('expiration_time', models.PositiveIntegerField()),
                ('logincount', models.PositiveIntegerField()),
                ('lastlogin', models.DateTimeField(blank=True, null=True)),
                ('last_ip', models.CharField(max_length=100)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('character_slots', models.PositiveIntegerField()),
                ('pincode', models.CharField(max_length=4)),
                ('pincode_change', models.PositiveIntegerField()),
                ('vip_time', models.PositiveIntegerField()),
                ('old_group', models.IntegerField()),
            ],
            options={
                'db_table': 'login2',
                'managed': False,
            },
        ),
    ]
