# Generated by Django 2.2.1 on 2019-05-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='birthdate',
            field=models.DateField(blank=True, default='2019-05-19', null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1, verbose_name='Gender'),
        ),
    ]
