# Generated by Django 2.2.1 on 2019-05-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190519_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='sex',
            field=models.CharField(choices=[('M', '👦🏻'), ('F', '👧🏻')], default='F', max_length=1, verbose_name='Gender'),
        ),
    ]
