# Generated by Django 3.0.2 on 2020-02-01 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_login'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE `login` CHANGE `account_id` `account_id` int(11) NOT NULL auto_increment COMMENT '' FIRST;"
        ),
        migrations.RunSQL(
            "ALTER TABLE `login` CHANGE `userid` `userid` varchar(23) NOT NULL COMMENT '' AFTER `account_id`;"
        ),
        migrations.RunSQL(
            "ALTER TABLE `login` CHANGE `user_pass` `user_pass` varchar(32) NOT NULL COMMENT '' AFTER `userid`;"
        ),
        migrations.RunSQL(
            "ALTER TABLE `login` CHANGE `sex` `sex` varchar(1) NOT NULL COMMENT '' AFTER `user_pass`;"
        ),
        migrations.RunSQL(
            "ALTER TABLE `login` CHANGE `email` `email` varchar(39) NOT NULL COMMENT '' AFTER `sex`;"
        ),
        migrations.RunSQL(
            "ALTER TABLE `login` CHANGE `group_id` `group_id` int(11) NOT NULL COMMENT '' AFTER `email`;"
        ),
        migrations.RunSQL(
            "ALTER TABLE `login` CHANGE `state` `state` int(10) unsigned NOT NULL COMMENT '' AFTER `group_id`;"
        ),
        migrations.RunSQL(
            "ALTER TABLE `login` CHANGE `unban_time` `unban_time` int(10) unsigned NOT NULL COMMENT '' AFTER `state`;"
        ),
        migrations.RunSQL(
            "ALTER TABLE `login` CHANGE `expiration_time` `expiration_time` int(10) unsigned NOT NULL COMMENT '' AFTER `unban_time`;"
        ),
        migrations.RunSQL(
            "ALTER TABLE `login` CHANGE `logincount` `logincount` int(10) unsigned NOT NULL COMMENT '' AFTER `expiration_time`;"
        ),
        migrations.RunSQL(
            "ALTER TABLE `login` CHANGE `lastlogin` `lastlogin` datetime(6) NULL COMMENT '' AFTER `logincount`;"
        ),
        migrations.RunSQL(
            "ALTER TABLE `login` CHANGE `last_ip` `last_ip` varchar(100) NOT NULL COMMENT '' AFTER `lastlogin`;"
        ),
        migrations.RunSQL(
            "ALTER TABLE `login` CHANGE `birthdate` `birthdate` date NULL COMMENT '' AFTER `last_ip`;"
        ),
        migrations.RunSQL(
            "ALTER TABLE `login` CHANGE `character_slots` `character_slots` int(10) unsigned NOT NULL COMMENT '' AFTER `birthdate`;"
        ),
        migrations.RunSQL(
            "ALTER TABLE `login` CHANGE `pincode` `pincode` varchar(4) NOT NULL COMMENT '' AFTER `character_slots`;"
        ),
        migrations.RunSQL(
            "ALTER TABLE `login` CHANGE `pincode_change` `pincode_change` int(10) unsigned NOT NULL COMMENT '' AFTER `pincode`;"
        ),
        migrations.RunSQL(
            "ALTER TABLE `login` CHANGE `vip_time` `vip_time` int(10) unsigned NOT NULL COMMENT '' AFTER `pincode_change`;"
        ),
        migrations.RunSQL(
            "ALTER TABLE `login` CHANGE `old_group` `old_group` int(11) NOT NULL COMMENT '' AFTER `vip_time`;"
        )
    ]
