# Generated by Django 2.2.1 on 2020-01-02 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190519_0304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login',
            options={'managed': False, 'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
    ]
