# Generated by Django 3.0.2 on 2020-02-02 00:19

from django.db import migrations
from django.forms.models import model_to_dict

def migrate_data(apps, schema_editor):
    old_logins = apps.get_model("users", "Login2")
    new_login = apps.get_model("users", "Login")

    for item in old_logins.objects.all():
        data_dict = model_to_dict(item)

        data_dict['id'] = data_dict['account_id']
        del data_dict['account_id']

        data_dict['username'] = data_dict['userid']
        del data_dict['userid']

        data_dict['password'] = data_dict['user_pass']
        del data_dict['user_pass']

        data_dict['last_login'] = data_dict['lastlogin']
        del data_dict['lastlogin']

        l = new_login(**data_dict)
        l.save()

        item.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_reorder_columns'),
    ]

    operations = [
        migrations.RunPython(migrate_data)
    ]
