# Generated by Django 2.2.1 on 2019-05-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190519_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='state',
            field=models.PositiveIntegerField(choices=[(0, 'Active ✅'), (1, 'Banned ❌')], default=0, verbose_name='RO State'),
        ),
    ]
