# Generated by Django 3.0.7 on 2020-12-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201219_2119'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE `login` CHANGE `web_auth_token` `web_auth_token` int(11) NULL COMMENT '';"
        )
    ]
