# Generated by Django 2.2.1 on 2019-05-19 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Char',
            fields=[
                ('char_id', models.AutoField(primary_key=True, serialize=False)),
                ('char_num', models.IntegerField()),
                ('name', models.CharField(max_length=30, unique=True)),
                ('class_field', models.PositiveSmallIntegerField(db_column='class')),
                ('base_level', models.PositiveSmallIntegerField()),
                ('job_level', models.PositiveSmallIntegerField()),
                ('base_exp', models.BigIntegerField()),
                ('job_exp', models.BigIntegerField()),
                ('zeny', models.PositiveIntegerField()),
                ('str', models.PositiveSmallIntegerField()),
                ('agi', models.PositiveSmallIntegerField()),
                ('vit', models.PositiveSmallIntegerField()),
                ('int', models.PositiveSmallIntegerField()),
                ('dex', models.PositiveSmallIntegerField()),
                ('luk', models.PositiveSmallIntegerField()),
                ('max_hp', models.PositiveIntegerField()),
                ('hp', models.PositiveIntegerField()),
                ('max_sp', models.PositiveIntegerField()),
                ('sp', models.PositiveIntegerField()),
                ('status_point', models.PositiveIntegerField()),
                ('skill_point', models.PositiveIntegerField()),
                ('option', models.IntegerField()),
                ('karma', models.IntegerField()),
                ('manner', models.SmallIntegerField()),
                ('party_id', models.PositiveIntegerField()),
                ('guild_id', models.PositiveIntegerField()),
                ('pet_id', models.PositiveIntegerField()),
                ('homun_id', models.PositiveIntegerField()),
                ('elemental_id', models.PositiveIntegerField()),
                ('hair', models.PositiveIntegerField()),
                ('hair_color', models.PositiveSmallIntegerField()),
                ('clothes_color', models.PositiveSmallIntegerField()),
                ('body', models.PositiveSmallIntegerField()),
                ('weapon', models.PositiveSmallIntegerField()),
                ('shield', models.PositiveSmallIntegerField()),
                ('head_top', models.PositiveSmallIntegerField()),
                ('head_mid', models.PositiveSmallIntegerField()),
                ('head_bottom', models.PositiveSmallIntegerField()),
                ('robe', models.PositiveSmallIntegerField()),
                ('last_map', models.CharField(max_length=11)),
                ('last_x', models.PositiveSmallIntegerField()),
                ('last_y', models.PositiveSmallIntegerField()),
                ('save_map', models.CharField(max_length=11)),
                ('save_x', models.PositiveSmallIntegerField()),
                ('save_y', models.PositiveSmallIntegerField()),
                ('partner_id', models.PositiveIntegerField()),
                ('online', models.IntegerField()),
                ('father', models.PositiveIntegerField()),
                ('mother', models.PositiveIntegerField()),
                ('child', models.PositiveIntegerField()),
                ('fame', models.PositiveIntegerField()),
                ('rename', models.PositiveSmallIntegerField()),
                ('delete_date', models.PositiveIntegerField()),
                ('moves', models.PositiveIntegerField()),
                ('unban_time', models.PositiveIntegerField()),
                ('font', models.PositiveIntegerField()),
                ('uniqueitem_counter', models.PositiveIntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('hotkey_rowshift', models.PositiveIntegerField()),
                ('clan_id', models.PositiveIntegerField()),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('title_id', models.PositiveIntegerField()),
                ('show_equip', models.PositiveIntegerField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'char',
                'managed': True,
            },
        ),
    ]
