# Generated by Django 2.2.1 on 2019-05-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char', '0003_auto_20190519_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='char',
            name='online',
            field=models.IntegerField(choices=[(0, ''), (1, '')]),
        ),
    ]
