# Generated by Django 2.2.1 on 2019-05-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char', '0004_auto_20190520_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='char',
            name='online',
            field=models.IntegerField(),
        ),
    ]
