# Generated by Django 3.0.7 on 2021-03-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='available_since',
            field=models.DateTimeField(default=None, help_text='Date and time when this update will start rolling out. NULL = now, use server timezone', null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='changelog',
            field=models.CharField(default=None, help_text='What is this update about?', max_length=256, null=True),
        ),
    ]
