# Generated by Django 3.0.7 on 2020-10-06 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the post', max_length=256)),
                ('content', models.TextField(blank=True, help_text='The body of the post', null=True)),
                ('reference', models.CharField(help_text='Link to original post in case it comes from another social network', max_length=2048)),
                ('added', models.DateTimeField(auto_now_add=True, help_text='Date when it was created on RagCP')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date when modified')),
                ('author', models.ForeignKey(help_text='Account that created this entry. In case it comes from another social network, it will use any system account', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(default=None, help_text='Foreign key to another post in case it is a response', null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Post')),
            ],
        ),
    ]