# Generated by Django 3.0.7 on 2020-10-10 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(help_text='Account that created this entry. In case it comes from another social network, it will use any system account', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(default=None, help_text='Foreign key to another post in case it is a response', null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Post', verbose_name='In response to'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reference',
            field=models.CharField(default=None, help_text='Link to original post in case it comes from another social network', max_length=2048, null=True),
        ),
    ]