# Generated by Django 3.0.7 on 2020-10-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20201011_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='scoring',
            field=models.FloatField(default=None, max_length=28, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='scoring_label',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
